---
- name: install tools from ubuntu repositories
  become: yes
  become_method: sudo
  apt: pkg="{{ item }}" state=latest
  with_items:
  # - gcc-arm-linux-androidabi
  # - gcc-i686-linux-android
  - jmtpfs
  - sqlcipher
  - sqlite3
  - sqlitebrowser
  # - sqliteman
  # - keepnote
  - qemu
  - qemu-system
  - qemu-system-arm
  - qemu-user
  - qemu-utils
  - jasmin-sable
  - meld
  - python3-meld3


- name: notsure where this fits
  become: yes
  become_method: sudo
  apt: pkg="{{ item }}" state=latest
  with_items:
  # - python3-frida
  - geany
  - geany-plugin-treebrowser
  
# - name: Tools utilities created by anantshri
#   become: yes
#   become_method: sudo
#   apt: pkg="{{ item }}" state=latest
#   with_items:
#   - apk2java
#   - drozer-checks
#   - androidtamer-adb



- name: optional packages but might be useful
  become: yes
  become_method: sudo
  apt: pkg="{{ item }}" state=latest
  with_items:
  - openvpn
  # - pdfcrack
  # - ratproxy 
  - proxychains
  - tsocks
  - redsocks
  - websockify
  - wifite
  - chaosreader
  - dsniff
  # - iceweasel
  - chromium

