---
- name: Install PyCurl (required for apt-repository updates)
  become: yes
  become_method: sudo
  apt: pkg="{{ item }}" state=latest
  with_items:
  - python3-pycurl
  - apt-transport-https

# - name: Configure android Tamer repository
#   become: yes
#   become_method: sudo
#   apt_repository: repo="deb https://repo.androidtamer.com Tamer5 main"



# # - lineinfile: dest=/etc/apt/source.list.d/androidtamer 
# #               line="deb http://repo.androidtamer.com Tamer4 main"  
# #               state=present  
# #               owner=root 
# #               group=root 
# #               mode=0644
# #               create=True

# - name: Adding Apt key
#   become: yes
#   become_method: sudo
#   apt_key: id=7EE83BCF url=https://repo.androidtamer.com/tamer.gpg.key state=present
- name: add update repository
  become: yes
  become_method: sudo
  apt_repository: repo='deb https://deb.debian.org/debian bullseye-updates main contrib' state=present update_cache=yes

- name: add backports repository
  become: yes
  become_method: sudo
  apt_repository: repo='deb https://deb.debian.org/debian bullseye-backports main contrib non-free' state=present update_cache=yes

- name: add non-free repository
  become: yes
  become_method: sudo
  apt_repository: repo='deb https://deb.debian.org/debian/ bullseye main contrib non-free' state=present update_cache=yes

- name: add security repository
  become: yes
  become_method: sudo
  apt_repository: repo='deb https://security.debian.org/debian-security bullseye-security main contrib' state=present update_cache=yes


#- name: Configure Ubuntu Mate official repositories
#    become: yes
#    become_method: sudo
#  apt_repository: repo="ppa:ubuntu-mate-dev/ppa"

#- name: add trusty Mate
#    become: yes
#   become_method: sudo
#  apt_repository: repo="ppa:ubuntu-mate-dev/trusty-mate"
