---
# - name: install packages essential for tamer Specific  UI
#   become: yes
#   become_method: sudo
#   apt: pkg="{{ item }}" state=latest
#   with_items:
#   - androidtamer-menu
#   - androidtamer-menuitems
  

# Change default Terminal to Terminator. SEt profile

- name: Set terminator as default shell
  command: update-alternatives --set x-terminal-emulator /usr/bin/terminator
  become: yes
  become_method: sudo

#- name: change grub boot menu image

#- name: grub customization

#- name: bootscreen splash

#- name: change taskbar menu items

#- name: change lightdm gtk greater screen

#- name: set default font to roboto


#- name: change defaults
#desktop/applications/media exec 
#desktop/applications/terminal exec
